version: "3.3"
services:
    postgres:
        image: postgres:10.3
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
    usuarios_api:
        image: node:16
        volumes: 
            - ./usuarios-api:/home/node/app
        user: node
        working_dir: /home/node/app/
        command: "npm start"
        links:
            - postgres
        ports:
            - ${PORT}:8080
        environment:
            - DB_HOST=postgres
        depends_on:
            - postgres
volumes:
    postgres:  

