version: "3.3"
services:
    postgres:
        image: postgres:10.3
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
        # ports:
        #     - 5432:5432
    usuarios_api:
        image: node:16
        volumes: 
            - ./usuarios-api:/home/node/app
        user: node
        working_dir: /home/node/app/
        command: "npm start"
        links:
            - postgres
        # ports:
        #     - ${USERS_API_PORT}:${USERS_API_PORT}
        environment:
            - DB_HOST=postgres
        depends_on:
            - postgres
    eventos_api:
        image: node:16
        volumes: 
            - ./agenda-api:/home/node/app
        user: node
        working_dir: /home/node/app/
        command: "npm start"
        links:
            - postgres
        # ports:
        #     - ${EVENTS_API_PORT}:${EVENTS_API_PORT}
        environment:
            - DB_HOST=postgres
        depends_on:
            - postgres
    notas_api:
        image: node:16
        volumes: 
            - ./nota-api:/home/node/app
        user: node
        working_dir: /home/node/app/
        command: "npm start"
        links:
            - postgres
        # ports:
        #     - ${NOTES_API_PORT}:${NOTES_API_PORT}
        environment:
            - DB_HOST=postgres
        depends_on:
            - postgres
    chat:
        image: alethetwin/python-tensorflow
        volumes:
            - ./chatbot-api:/app
        working_dir: /app/
        # ports:
        #     - 8000:8000
        command: "bash run.sh"
    lamp:
        image: alethetwin/lamp:amd64
        # ports:
        #     - 80:80
        volumes: 
            - ./cliente/db:/var/lib/mysql
            - ./cliente/app:/app
        command: 
            - /run.sh
        environment:
            MYSQL_ADMIN_PASS: 123456
            PHP_VERSION: 8.1
    proxy:
        image: nginx
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - usuarios_api
            - eventos_api
            - notas_api
            - lamp
            - chat
volumes:
    postgres:  

