version: "3.3"
services:
    chat:
        image: alethetwin/python-tensorflow
        volumes:
            - ./:/app
        working_dir: /app/
        ports:
            - 8000:8000
        command: 'bash run.sh "añade un evento para hoy"'